### ISSUE TITLE
detected invalid summary file when index with FAST5 in multiple subdirectories

### ISSUE THREAD

**Issue by huangnengCSU** [hasindu2008/f5c#85] opened 2021-03-30 03:08 UTC
Hi,
    I am using f5c to generate index file. First, the raw fast5 files are in two directories. I used two Guppy basecallers to baseball the raw reads, separately. Then I merged two basecalling results including fastq and sequencing-summary. Then I used the following command to generate index.
```
f5c_x86_64_linux index -t 40 -s merged_summary.txt -d Bham -d Norwich NA12878-10X-gpoup2.fastq
```
Then I met the warning information as follows:
```
warning: detected invalid summary file entries for 5052927 of 5052927 fast5 files
These files will be indexed without using the summary file, which is slow.
```
Next, I used Nanopolish to generate the index file with the following command, and there are no warnings.
```
nanopolish index -s merged_summary.txt -d Bham -d Norwich NA12878-10X-gpoup2.fastq
```
Can you help me to fix this problem? Thanks.

Best 
Neng Huang

**Comment by hasindu2008** [comment] 2021-03-30 03:26
Hi @huangnengCSU 

Could you please do a `head  merged_summary.txt`? It is likely that the summary file format changed again.

Alternatively, can you do `f5c_x86_64_linux index -t 40  --iop 40 -d Bham -d Norwich NA12878-10X-gpoup2.fastq`?
This will index from the fast5 files (without using sequencing summary) but (--iop) will spawn 40 multiple processes to perform parallel fast5 I/O. It tends to have comparable performance to that of using sequencing summary but eliminates many traps caused by inconsistency in sequencing summary files. I usually use this method where a PromethION sample can be indexed in like half an hour.

**Comment by huangnengCSU** [comment] 2021-03-30 03:37
Hi,
    First, the head of `merged_summary.txt` is like:
```
filename	read_id	run_id	batch_id	channel	mux	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template	scaling_median_template	scaling_mad_template
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch84_read16403_strand.fast5	d0e527e9-bda5-4a8a-8e35-eceed36d7195	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	84	3	37430.340750	1.039250	831	TRUE	37430.385750	795	0.994250	228	11.964715	0.000000	100.258179	10.025818	101.208977	11.970220
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch448_read35_strand.fast5	228201a5-1575-474f-bbea-0a9ddfa32049	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	448	3	32.414500	316.377500	253102	TRUE	32.414500	253102	316.377500	138830	10.957945	0.000000	108.461121	10.208106	99.251411	11.399777
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch312_read9340_strand.fast5	7520533d-fb76-4f00-b257-b586939e01a3	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	312	4	65436.859500	316.363000	253090	TRUE	65436.872000	253080	316.350500	64959	10.214883	0.000000	100.805046	10.390393	112.906784	15.982340
nanopore2_20170308_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_78206_ch199_read798_strand.fast5	4d26f851-1749-4b91-b42d-811211e0a754	a90506a76264c2f48994765f206637ef2404e8ef	0	199	3	1470.354000	1.594000	1275	FALSE	1470.399000	1239	1.549000	268	8.098982	0.000000	120.055283	7.298193	122.081337	13.275729
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch435_read10414_strand.fast5	5217de0c-76df-40db-ba4f-c0d95d296190	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	435	2	62778.701250	12.851000	10280	TRUE	62778.738750	10250	12.813500	3755	10.223731	0.000000	88.227203	8.385230	85.226517	10.543069
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch210_read2830_strand.fast5	e988df05-abc5-4407-a50c-048fcb7c6a53	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	210	4	22973.132000	41.073250	32858	FALSE	22973.167000	32830	41.038250	2078	3.487839	0.000000	102.263344	5.833203	109.861313	12.917638
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch398_read4274_strand.fast5	35eac533-5c65-404f-aaed-cc29e6b141d4	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	398	2	63352.446500	30.801500	24641	FALSE	63352.446500	24641	30.801500	70	3.666289	0.000000	116.299492	4.557190	111.591370	14.609043
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch256_read1073_strand.fast5	d91c321d-f7c1-432a-8811-22bee83857f0	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	256	2	4368.279000	117.681250	94145	TRUE	4368.320250	94112	117.640000	49030	10.171406	0.000000	105.726807	10.390393	106.481216	11.311064
nanopore2_20170307_FNFAF09713_MN17024_sequencing_run_20170307_NA12878_PC_RAD002_33603_ch374_read4454_strand.fast5	8ebf3ffb-61af-4bc2-8af5-94ed500ca129	fb85a638c2b951a2234e74acb8b6261d86fe9c80	0	374	2	51375.793750	29.700500	23760	FALSE	51375.796250	23758	29.698000	34	3.602321	0.000000	97.159294	6.926929	102.002762	12.767143
```
  Second, the data I used is human NA12878 35X, and the Fastq file size is about 200G. I think If the summary file is not used, the index process may be time-consuming.

**Comment by hasindu2008** [comment] 2021-03-30 04:08
@huangnengCSU 

Your sequencing summary file looks alright. Can you please give the _f5c_ and _nanopolish_ version you tried it with?

With _--iop 64_, f5c index could do a 50X NA12878 in around an hour without the sequencing summary file. It depends on the storage system though - is your storage system a single disk or a RAID system/cluster storage? 
An example on our cluster storage:
```
[f5c_index_iop] Parallel indexing done - took 2245.161s
[index_main] Readdb built - took 1513.980s
[f5c_index_merge] Indexing merging done - took 39.698s.
[readdb] num reads: 11903327, num reads with path to fast5: 11903327
[index_main] Readdb saved - took 15.203s
[main] CMD: f5c index -d fast5/ --iop 64 -t 32 -v2 /scratch_local/reads.fastq
[main] Real time: 3828.889 sec; CPU time: 28357.446 sec; Peak RAM: 3.941 GB
```

`-t` is for writing the bgzf index file and will work and improves performance with or without the summary file. `--iop` option is for fast5 based indexing only and cannot be used with the summary file. On the storage systems (cluster and RAID storage) that I have tested, fast5 based indexing with `--iop`  has a similar performance to using the summary file.

**Comment by huangnengCSU** [comment] 2021-03-30 06:24
f5c version: 0.6
nanopolish version: 0.13.2
I have tested the `--iop 40` and `-t 40` on the data of NA12878 10X：
```
Command being timed: "f5c_x86_64_linux index -t 40 --iop 40 -d Bham -d Norwich -d Notts -d UBC -d UCSC NA12878-10X-gpoup2.fastq"
	User time (seconds): 10094.42
	System time (seconds): 9337.30
	Percent of CPU this job got: 393%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:22:15
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1851812
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 66
	Minor (reclaiming a frame) page faults: 7487441
	Voluntary context switches: 57022794
	Involuntary context switches: 1089457
	Swaps: 0
	File system inputs: 188672168
	File system outputs: 25895424
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by hasindu2008** [comment] 2021-04-09 22:34
@huangnengCSU 

I am trying to locate the bug in f5c that affects your sequencing summary file. Is your dataset with the sequencing summary files public? Is it giving the problem only when the data is in multiple subdirectories?

**Comment by huangnengCSU** [comment] 2021-04-12 02:16
@hasindu2008 
The raw signals of NA12878 are from the public website https://github.com/nanopore-wgs-consortium/NA12878. I divided the raw signals into two subdirectories the used Guppy to basecalling the raw signals. The sequencing summary was generated by Guppy.

**Comment by hasindu2008** [comment] 2021-05-08 08:53
Sorry for taking this long. Finally got time to find the potential issue and fix it. If you still have you dataset could you please check if the issue is fixed in the latest commit in _dev_ branch at https://github.com/hasindu2008/f5c/tree/dev. For your convenience, I am attaching some compiled binaries.

[f5c-v0.6-32-gd611299-binaries.tar.gz](https://github.com/hasindu2008/f5c/files/6445551/f5c-v0.6-32-gd611299-binaries.tar.gz)

**Comment by hasindu2008** [comment] 2021-08-20 02:26
This is fixed in the latest release I hope. Feel free to reopen if the problem still exists.

**Closed by hasindu2008** 2021-08-20 02:26 UTC
