### ISSUE TITLE
Question: Directory of blow5:s as input?

### ISSUE THREAD

**Issue by kpalin** [hasindu2008/f5c#107] opened 2022-03-23 13:02 UTC
Reading f5c documentation in preparation for moving my pipeline from fast5 to blow5, I noticed that f5c appears to want only a single blow5 file as input. Is that right?   

I would like to keep the old fast5 type architecture of ~189 files of ~8GB each rather than one blow5 file of 763GB (example for one sample), which, I think, is about 5% of maximum file size (16TB) on NetApp. And I would expect it to be cumbersome to work with too.  Have I misunderstood something or is the "one humongous file" the recommended workflow for blow5?

Thanks in advance,
Kimmo

**Comment by hasindu2008** [comment] 2022-03-23 23:47
Hi @kpalin 

You are right. The current implementation of f5c takes one single BLOW5 file.  This is mainly due to the convenience of implementation but also followed by the following benefits.
1. While doing random access*, it is efficient to access a single file, rather than opening and closing multiple files each time (having thousands of files open is also not a good idea)
2. The index becomes portable as there are no files path involved - so the BLOW5 file can be moved with the index elsewhere and used directly without the need to reindex
3. Less prone to user errors caused by relative paths (if you index while being on a certain directory, and then run later from another path multi-file approach runs into trouble)

For archiving whether it is good to have a single large file or multiple files depends on different factors I believe. My personal preference is having one file per sequencing run as I find it easy to manage and having an index stored for such a file allows us to extract one or reads quickly if later needed. On the other hand, some old file systems like FAT32 has a 4GB file size limit,  so a single file is not possible. Fear of corruption is another factor, but as most large storage systems nowadays are RAID-based this is extremely rare I think. What are your thoughts on the disadvantages of having large files other than this?

About the recommended workflow: the recommended workflow is to perform sequential disk access as much as possible and in this case, having single or multi-files does not matter. But for random access, a single file has benefits as I mentioned above.

To provide all these different options we made slow5tools such that one could easily go back and forth between single or multiple files (merge and split). They perform sequential access, so should be quick - have you done a test on your system? I think a 30X PromethION set would take like 1-3 hours for merging (depends on the number of threads you use and sequential disk access bandwidth) and the time spent here would be saved during later steps with no requirement for opening/closing multiple files.  This way you can keep the old fast5 type architecture, but can temporarily merge before calling f5c. The next release of slow5tools will feature "cat" subtool that can be used to merge multiple files from same run even faster (at speed of copying).

*The main reason for this is f5c was designed following the nanopolish approach for FAST5 files: such that it iterates sequentially through the BAM files and for each read ID random access to the disk is performed. For FAST5 this makes sense as there is sequential access is not possible anyway. However, if I rewrite f5c from the scratch for BLOW5, I would rather sequentially iterate through one or more BLOW5 files while doing random access to BAM as it would be way efficient. This is something that I want to do but at the moment finding hard to find time.

**Comment by kpalin** [comment] 2022-03-24 06:31
I fully agree with you with the up- and downsides of large vs multiple files.  In addition I'm concerned that in general things tend to start breaking or misbehaving when pushed to extreme (large files, many files, etc...  running `ls` in a directory with 10k:s of files is an example)

I think I'll go forward with creating huge temporary files with slow5tools cat or merge.    Would I get the same f5c output by first splitting the bam file to match individual blow5:s?  I usually have only ~300 files so the splitting would be quick.

**Comment by hasindu2008** [comment] 2022-03-24 10:07
Yes, f5c calls methylation independently on each read alignment record. So if you somehow split the BAM file such that each BAM file has the same reads as the BLOW5 file that you would input to f5c (note: each split BAM should be sorted in genomic coordinates), it will generate the same results.

**Comment by hasindu2008** [comment] 2022-05-15 08:52
As this feature requires a lot of code refactoring and because there are alternate methods to achieve them I will not implement this feature in near future. Please reopen if it becomes a serious issue.

**Closed by hasindu2008** 2022-05-15 08:52 UTC
